### ISSUE TITLE
light theme dark theme

### ISSUE THREAD

**Issue by kokqi** [Xezard/DevMC#4]
can you make a light theme and dark theme switcher button

**Comment by Xezard** [comment]
![3c7f68e3f](https://user-images.githubusercontent.com/17483454/189923299-4f36268a-2c6e-4e1c-a694-7a99dc3a4c75.gif)

I've been working on a big update of the site for about 3 weeks now. This update has already implemented the ability to change the theme of the site in one click. Once I'm done with the update I'll update the site and try to write an article about it. Since, unexpectedly for me, the resource began to rapidly gain popularity - I had big plans for it. Thank you.

**Comment by Xezard** [comment]
Rolled out site update.
